import hmac

from fastapi import Header, HTTPException, status

from control_plane.config import settings
from control_plane.observability import get_logger

logger = get_logger("control_plane.auth")


def _constant_time_eq(a: str, b: str) -> bool:
    return hmac.compare_digest(a.encode(), b.encode())


async def require_api_key(x_api_key: str = Header(default=None, alias="X-API-Key")):
    if not settings.AUTH_ENABLED:
        return
    if not x_api_key or not _constant_time_eq(x_api_key, settings.API_KEY):
        logger.warning("auth_rejected", extra={"reason": "invalid_or_missing_api_key"})
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or invalid X-API-Key header.",
        )


async def require_registration_token(x_registration_token: str = Header(default=None, alias="X-Registration-Token")):
    if not settings.AUTH_ENABLED:
        return
    if not x_registration_token or not _constant_time_eq(x_registration_token, settings.REGISTRATION_TOKEN):
        logger.warning("auth_rejected", extra={"reason": "invalid_or_missing_registration_token"})
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing or invalid X-Registration-Token header.",
        )


def log_effective_auth_config():
    if not settings.AUTH_ENABLED:
        logger.warning(
            "auth_disabled",
            extra={"warning": "CP_AUTH_ENABLED=false -- all endpoints are UNAUTHENTICATED. "
                               "Do not use this mode outside local development."},
        )
        return

    if settings._API_KEY_WAS_GENERATED:
        logger.warning(
            "api_key_autogenerated",
            extra={"api_key": settings.API_KEY,
                   "hint": "Set CP_API_KEY to pin this value across restarts."},
        )
    if settings._REGISTRATION_TOKEN_WAS_GENERATED:
        logger.warning(
            "registration_token_autogenerated",
            extra={"registration_token": settings.REGISTRATION_TOKEN,
                   "hint": "Set CP_REGISTRATION_TOKEN to pin this value across restarts."},
        )
